// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHbafSs3z5pI4sEcFs-6Wr9N3BlNihPs',
    appId: '1:500075678183:web:23d743a6d7bb3fb5dbd542',
    messagingSenderId: '500075678183',
    projectId: 'tpmmm-a8ab9',
    authDomain: 'tpmmm-a8ab9.firebaseapp.com',
    storageBucket: 'tpmmm-a8ab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjWiUJgRpCto2CFigmbjTbuhWibMY3ac',
    appId: '1:500075678183:android:6ebcdc5f29fab451dbd542',
    messagingSenderId: '500075678183',
    projectId: 'tpmmm-a8ab9',
    storageBucket: 'tpmmm-a8ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg4cr5557svG2vEUkLEbnMLsFGtsj8Ydw',
    appId: '1:500075678183:ios:c9d08cab932a5b65dbd542',
    messagingSenderId: '500075678183',
    projectId: 'tpmmm-a8ab9',
    storageBucket: 'tpmmm-a8ab9.firebasestorage.app',
    iosBundleId: 'com.istic.transMusicales',
  );
}
